/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InsertionSort;

public class Library {
    public static void main(String[] args) {
        int[] arr1= new int[]{20, 1, 12, 8, 5, -2};

        sort(arr1);
        for (int i = 0; i < arr1.length; i++) {
            System.out.println(arr1[i]);
        }
        System.out.println();
    }
    public boolean someLibraryMethod() {
        return true;
    }

    static void sort(int arr[])
    {
        int n = arr.length;
        for (int i = 1; i < n; ++i) {
            int key = arr[i];
            int j = i - 1;

            while (j >= 0 && arr[j] > key) {
                arr[j + 1] = arr[j];
                j--;
            }
            arr[j + 1] = key;
        }

    }
}

